# set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-terminal "screen-256color"
set -g mouse on

# set indexing from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Status bar position top or bottom
set-option -g status-position top

# source tmux
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# open Windows


# Open panes in current directory
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"


# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'


run '~/.tmux/plugins/tpm/tpm'
