
preload = ~/Pictures/wallpapers/catppuccin-twilight.png
wallpaper = ,~/Pictures/wallpapers/catppuccin-twilight.png

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

