
preload = ~/Pictures/wallpapers/arch-black-4k.png
wallpaper = ,~/Pictures/wallpapers/arch-black-4k.png

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off

